### ISSUE TITLE
Docker instructions do not seem to work.

### ISSUE THREAD

**Issue by desilinguist** [sigedu-org/website#41]
Hi @lpmi-13, 

The docker instructions do not seem to work for me. Can you please take a look at it?

**Comment by lpmi-13** [comment]
Hi there,

Sure, happy to take a look. Just a few questions so I can try and replicate the issue:

- which operating system are you using?
- which command is failing?
- what happens (output on the screen, etc)  when it fails?

**Comment by desilinguist** [comment]
I am using macOS 10.14.6 and Docker version `version 19.03.1, build 74b1e89`. 

I ran the following command in the root of the repo per the README: 

```docker build -t nitin/nitin .```

It successfully pulled the jekyll/jekyll image from dockerhub and then started running the other steps in the Dockerfile but then failed at step 3/6. The full log is below: 

```bash
Sending build context to Docker daemon  27.06MB
Step 1/6 : FROM jekyll/jekyll
latest: Pulling from jekyll/jekyll
9d48c3bd43c5: Pull complete 
9ce9598067e7: Pull complete 
278f4c997324: Pull complete 
bfca09e5fd9a: Pull complete 
2612f15b9d22: Pull complete 
c6d47e0a466d: Pull complete 
Digest: sha256:83c68abcc64b39d4d446e9c97be28dbe47ba40f22fa090458a39c4af70521be8
Status: Downloaded newer image for jekyll/jekyll:latest
 ---> d57b6d71e262
Step 2/6 : COPY ./Gemfile ./
 ---> b933f82876dc
Step 3/6 : RUN bundle install
 ---> Running in 57f733e1989e

[!] There was an error parsing `Gemfile`: There are no gemspecs at /srv/jekyll. Bundler cannot continue.

 #  from /srv/jekyll/Gemfile:2
 #  -------------------------------------------
 #  source "https://rubygems.org"
 >  gemspec
 #  -------------------------------------------
The command '/bin/sh -c bundle install' returned a non-zero code: 15
```

**Comment by lpmi-13** [comment]
Looks like it was an issue with the .gemspec file. I've opened a pull request with an updated Dockerfile that fixes the issue.

There's one warning during the build (harmless...it's about the git discovery across file systems, so we can safely ignore) that is now suppressed. There's another one involving the `git -ls` command present in the .gemspec file, that is equally harmless and ignorable, but will take a bit of doing to successfully suppress during the build process. So I'd suggest it's not worth the effort, since it's one line, and we can ignore it anyway.

**Comment by desilinguist** [comment]
Thank you so much! I’ll test it tomorrow and merge!
